app-id: com.frigateNVR.ConfigGUI
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
command: frigate-config-gui
finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=x11
  # Wayland access
  - --socket=wayland
  # File system access for config files
  - --filesystem=home
  # Network access for updates and package installation
  - --share=network
  # Allow communication with host dbus
  - --socket=session-bus
  # For hardware acceleration
  - --device=dri
modules:
  - name: nodejs
    buildsystem: simple
    build-commands:
      - |
        tar xf node-v20.11.1-linux-x64.tar.xz
        cp -r node-v20.11.1-linux-x64/* /app/
    sources:
      - type: archive
        path: downloads/node-v20.11.1-linux-x64.tar.xz
        sha256: d8dab549b09672b03356aa2257699f3de3b58c96e74eb26a8b495fbdc9cf6fbe

  - name: frigate-config-gui
    buildsystem: simple
    build-commands:
      # Install npm dependencies (including TypeScript, React, and dev dependencies)
      - npm ci
      # Type check TypeScript
      - npm run type-check
      # Build TypeScript and bundle the application
      - npm run build
      # Install the application
      - cp -r dist/linux-unpacked/* /app/
      # Install desktop file and icons
      - install -Dm644 build/icon.png /app/share/icons/hicolor/512x512/apps/com.frigateNVR.ConfigGUI.png
      - install -Dm644 flatpak/com.frigateNVR.ConfigGUI.desktop /app/share/applications/com.frigateNVR.ConfigGUI.desktop
      - install -Dm644 flatpak/com.frigateNVR.ConfigGUI.appdata.xml /app/share/metainfo/com.frigateNVR.ConfigGUI.appdata.xml
    sources:
      - type: dir
        path: ../
