app-id: com.frigateNVR.ConfigGUI
runtime: org.freedesktop.Platform
runtime-version: '24.08'
sdk: org.freedesktop.Sdk
command: frigate-config-gui
sdk-extensions:
  - org.freedesktop.Sdk.Extension.node20

finish-args:
  # X11 + XShm access
  - --share=ipc
  - --socket=x11
  # Wayland access
  - --socket=wayland
  # File system access for config files
  - --filesystem=home
  # Network access for updates and package installation
  - --share=network
  # Allow communication with host dbus
  - --socket=session-bus
  # For hardware acceleration
  - --device=dri

build-options:
  env:
    NPM_CONFIG_LOGLEVEL: info
  append-path: /usr/lib/sdk/node20/bin
  prepend-pkg-config-path: /usr/lib/sdk/node20/lib/pkgconfig
  prepend-ld-library-path: /usr/lib/sdk/node20/lib

cleanup:
  - /include
  - /lib/pkgconfig
  - /share/doc
  - /share/man
  - '*.a'
  - '*.la'

modules:
  - name: frigate-config-gui
    buildsystem: simple
    build-commands:
      - |
        # Set up Node.js environment
        . /usr/lib/sdk/node20/enable.sh
        export FLATPAK_BUILDER_BUILDDIR="$PWD"
        export FLATPAK_ID="com.frigateNVR.ConfigGUI"

        # Install dependencies and build
        npm config set prefix /app
        npm ci --offline --cache=/run/build/frigate-config-gui/npm-cache
        npm run build

        # Install application
        mkdir -p /app/bin
        cp -r dist/linux-unpacked/* /app/
        mv /app/frigate-config-gui /app/bin/

        # Install desktop file and icons
        mkdir -p /app/share/icons/hicolor/512x512/apps
        mkdir -p /app/share/applications
        mkdir -p /app/share/metainfo
        cp build/icon.png /app/share/icons/hicolor/512x512/apps/${FLATPAK_ID}.png
        cp flatpak/${FLATPAK_ID}.desktop /app/share/applications/
        cp flatpak/${FLATPAK_ID}.appdata.xml /app/share/metainfo/

        # Create wrapper script
        cat > /app/bin/frigate-config-gui-wrapper << 'EOL'
        #!/bin/sh
        export PATH="/app/bin:$PATH"
        export NODE_PATH="/app/lib/node_modules"
        exec /app/bin/frigate-config-gui "$@"
        EOL
        chmod +x /app/bin/frigate-config-gui-wrapper
        ln -sf /app/bin/frigate-config-gui-wrapper /app/bin/frigate-config-gui
    sources:
      - type: dir
        path: .