name: Build Flatpak

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flatpak
        run: |
          sudo apt-get update
          sudo apt-get install -y flatpak flatpak-builder

      - name: Add Flathub remote and install dependencies
        run: |
          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          sudo flatpak install -y flathub \
            org.freedesktop.Platform//24.08 \
            org.freedesktop.Sdk//24.08 \
            org.freedesktop.Sdk.Extension.node20//24.08

      - name: Build Flatpak
        run: |
          chmod +x tools/build.sh
          ./tools/build.sh

      - name: Upload Flatpak bundle
        uses: actions/upload-artifact@v4
        with:
          name: frigate-config-gui-flatpak
          path: frigate-config-gui.flatpak

      - name: Create Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          files: frigate-config-gui.flatpak
          draft: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}